import turtle
import random

# Configuração inicial
turtle.speed(0)  # Velocidade máxima
turtle.bgcolor("black")
turtle.hideturtle()

# Função para desenhar uma explosão de fogos de artifício
def draw_firework(x, y):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()

    # Desenhar várias linhas coloridas para representar os raios do fogos de artifício
    for _ in range(30):
        # Cor aleatória para os raios
        color = random.choice(["red", "orange", "yellow", "green", "blue", "purple"])
        turtle.color(color)
        # Tamanho aleatório para os raios
        length = random.randint(50, 200)
        # Ângulo aleatório para os raios
        angle = random.randint(0, 360)
        turtle.setheading(angle)
        turtle.forward(length)
        turtle.backward(length)

    # Voltar para o centro
    turtle.penup()
    turtle.goto(0, 0)
    turtle.pendown()

# Evento de clique do mouse para gerar fogo